//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace XsdToClassT4.NewFolder1
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetDefinition {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetDefinitionResponse {
        
        private string getDefinitionResultField;
        
        /// <remarks/>
        public string GetDefinitionResult {
            get {
                return this.getDefinitionResultField;
            }
            set {
                this.getDefinitionResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class SetDefinition {
        
        private string usernameField;
        
        private string passwordField;
        
        private string xmlFavouriteField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string xmlFavourite {
            get {
                return this.xmlFavouriteField;
            }
            set {
                this.xmlFavouriteField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class SetDefinitionResponse {
        
        private long setDefinitionResultField;
        
        /// <remarks/>
        public long SetDefinitionResult {
            get {
                return this.setDefinitionResultField;
            }
            set {
                this.setDefinitionResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class BeginTransaction {
        
        private string usernameField;
        
        private string passwordField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class BeginTransactionResponse {
        
        private string beginTransactionResultField;
        
        /// <remarks/>
        public string BeginTransactionResult {
            get {
                return this.beginTransactionResultField;
            }
            set {
                this.beginTransactionResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class EndTransaction {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tidField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string tid {
            get {
                return this.tidField;
            }
            set {
                this.tidField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class EndTransactionResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class Execute {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string languageField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteResponse {
        
        private string executeResultField;
        
        /// <remarks/>
        public string ExecuteResult {
            get {
                return this.executeResultField;
            }
            set {
                this.executeResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteDefinition {
        
        private string usernameField;
        
        private string passwordField;
        
        private string favouriteXmlField;
        
        private string languageField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string favouriteXml {
            get {
                return this.favouriteXmlField;
            }
            set {
                this.favouriteXmlField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteDefinitionResponse {
        
        private string executeDefinitionResultField;
        
        /// <remarks/>
        public string ExecuteDefinitionResult {
            get {
                return this.executeDefinitionResultField;
            }
            set {
                this.executeDefinitionResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteSpreadsheet {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string languageField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteSpreadsheetResponse {
        
        private byte[] executeSpreadsheetResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExecuteSpreadsheetResult {
            get {
                return this.executeSpreadsheetResultField;
            }
            set {
                this.executeSpreadsheetResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteExport {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string languageField;
        
        private int maxTransesField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public int maxTranses {
            get {
                return this.maxTransesField;
            }
            set {
                this.maxTransesField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class ExecuteExportResponse {
        
        private byte[] executeExportResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExecuteExportResult {
            get {
                return this.executeExportResultField;
            }
            set {
                this.executeExportResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class DeleteInvalidFavourites {
        
        private string usernameField;
        
        private string passwordField;
        
        private int daysField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class DeleteInvalidFavouritesResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetFavouriteConditions {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string xmlTagField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string xmlTag {
            get {
                return this.xmlTagField;
            }
            set {
                this.xmlTagField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetFavouriteConditionsResponse {
        
        private string getFavouriteConditionsResultField;
        
        /// <remarks/>
        public string GetFavouriteConditionsResult {
            get {
                return this.getFavouriteConditionsResultField;
            }
            set {
                this.getFavouriteConditionsResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetFavouriteConditionsExpressionConcat {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string[] expressionField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string[] expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetFavouriteConditionsExpressionConcatResponse {
        
        private string getFavouriteConditionsExpressionConcatResultField;
        
        /// <remarks/>
        public string GetFavouriteConditionsExpressionConcatResult {
            get {
                return this.getFavouriteConditionsExpressionConcatResultField;
            }
            set {
                this.getFavouriteConditionsExpressionConcatResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetFavouriteConditionsDate {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string xmlTagField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string xmlTag {
            get {
                return this.xmlTagField;
            }
            set {
                this.xmlTagField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class GetFavouriteConditionsDateResponse {
        
        private string getFavouriteConditionsDateResultField;
        
        /// <remarks/>
        public string GetFavouriteConditionsDateResult {
            get {
                return this.getFavouriteConditionsDateResultField;
            }
            set {
                this.getFavouriteConditionsDateResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class IsLimitedByRestrictedAccess {
        
        private string usernameField;
        
        private string passwordField;
        
        private long favouriteField;
        
        private string[] xmlTagsField;
        
        private int applicationField;
        
        private string xmlParamField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public long favourite {
            get {
                return this.favouriteField;
            }
            set {
                this.favouriteField = value;
            }
        }
        
        /// <remarks/>
        public string[] xmlTags {
            get {
                return this.xmlTagsField;
            }
            set {
                this.xmlTagsField = value;
            }
        }
        
        /// <remarks/>
        public int application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public string xmlParam {
            get {
                return this.xmlParamField;
            }
            set {
                this.xmlParamField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://synergi.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://synergi.com", IsNullable=false)]
    public partial class IsLimitedByRestrictedAccessResponse {
        
        private bool isLimitedByRestrictedAccessResultField;
        
        /// <remarks/>
        public bool IsLimitedByRestrictedAccessResult {
            get {
                return this.isLimitedByRestrictedAccessResultField;
            }
            set {
                this.isLimitedByRestrictedAccessResultField = value;
            }
        }
    }
}
